import { Instance } from "cs_script/point_script";
import { persistOnReload } from "../shared/persist";

// The cs_minimap_volume entities come from maps/prefabs/dynamic_minimap.vmap, generated by
// `npm run update-minimap`. Every map's volume covers that map's own world area, so they all overlap
// and all start disabled - only the volume(s) of the map that's actually loaded get enabled.
// Must match namePrefix in src/minimap-generator/minimap.config.json.
const MINIMAP_VOLUME_PREFIX = "dynamic_minimap_";
// Multi-level maps (nuke, train, vertigo) get a second volume below their radar's split altitude.
const LOWER_SECTION_SUFFIX = "_lower";

// A round restart (mp_restartgame, warmup end, every new round) cleans up the map and respawns the
// volumes in their compiled StartDisabled state, so the active map is remembered and re-enabled
// from onRoundStart.
let activeMap: string | undefined;

const fireAtVolumes = (mapName: string, input: "Enable" | "Disable") => {
    for (const minimapName of [mapName, mapName + LOWER_SECTION_SUFFIX]) {
        Instance.EntFireAtName({ name: MINIMAP_VOLUME_PREFIX + minimapName, input });
    }
};

export const enableMinimap = (mapName: string): void => {
    activeMap = mapName;
    fireAtVolumes(mapName, "Enable");
};

export const disableMinimap = (mapName: string): void => {
    if (activeMap === mapName) activeMap = undefined;
    fireAtVolumes(mapName, "Disable");
};

export const onRoundStart = (): void => {
    if (activeMap) fireAtVolumes(activeMap, "Enable");
};

persistOnReload("minimap", {
    activeMap: { get: () => activeMap, set: (value) => { activeMap = value; } },
});
