// Text assets for each minimap volume, in the exact formats the game's own `cs_minimap_create`
// writes (see the working de_dust2/de_inferno setup):
//   content: panorama/images/overheadmaps/<level>_<minimap>_radar.tga (+ .txt texture settings)
//   content: panorama/dynamic_image_<level>_<minimap>.vpdi
//   game:    resource/overviews/<level>.txt  "Volumes" block, one entry per minimap_name

import type { MinimapVolume } from "./config.ts";

export const radarBaseName = (levelName: string, minimapName: string) => `${levelName}_${minimapName}_radar`;

export const dynamicImageName = (levelName: string, minimapName: string) => `dynamic_image_${levelName}_${minimapName}.vpdi`;

// Written by the game with LF line endings.
export const RADAR_TEXTURE_SETTINGS =
    '"settings"\n{\n\t"clampu" "1"\n\t"clampv" "1"\n\t"output_format" "IMAGE_FORMAT_RGBA8888"\n\t"nomip" "1"\n\n}\n';

export const dynamicImageManifest = (levelName: string, minimapName: string) =>
    [
        `"DynamicImages"`,
        `{`,
        `\t"Explicit Files"`,
        `\t{`,
        `\t\t"{images}/overheadmaps/${radarBaseName(levelName, minimapName)}.tga"\t\t""`,
        `\t}`,
        `}`,
        ``,
    ].join("\r\n");

const num = (n: number) => String(Object.is(n, -0) ? 0 : n);

const volumesBlock = (volumes: MinimapVolume[]) =>
    [
        `"Volumes"`,
        `\t{`,
        ...volumes.flatMap((volume) => [
            `\t\t"${volume.minimapName}"`,
            `\t\t{`,
            `\t\t\t"pos_x"\t\t"${num(volume.posX)}"`,
            `\t\t\t"pos_y"\t\t"${num(volume.posY)}"`,
            `\t\t\t"scale"\t\t"${num(volume.scale)}"`,
            `\t\t\t"autogenerated_tga"\t\t"1"`,
            `\t\t}`,
        ]),
        `\t}`,
    ].join("\n");

/**
 * Replaces (or adds) the "Volumes" block of the level overview. Everything else in the file - the
 * lobby level's own pos_x/pos_y/scale radar - is left exactly as it was.
 * @param existing Current file contents, if the file exists.
 */
export const mergeOverview = (existing: string | undefined, levelName: string, volumes: MinimapVolume[]): string => {
    const block = volumesBlock(volumes);
    if (existing === undefined || existing.trim() === "") {
        return `"${levelName}"\n{\n\t${block}\n}\n`;
    }

    const tokens = tokenizeKeyValues(existing);
    const isOpen = (i: number) => tokens[i] !== undefined && !tokens[i].quoted && tokens[i].text === "{";
    const isClose = (i: number) => !tokens[i].quoted && tokens[i].text === "}";
    const rootOpen = tokens.findIndex((_, i) => isOpen(i));
    if (rootOpen === -1) throw new Error("overview file has no root block");

    let depth = 0;
    let rootClose = -1;
    let volumesKey = -1;
    for (let i = rootOpen; i < tokens.length; i++) {
        const t = tokens[i];
        if (isOpen(i)) depth++;
        else if (isClose(i)) {
            depth--;
            if (depth === 0) {
                rootClose = i;
                break;
            }
        } else if (depth === 1 && t.quoted && t.text.toLowerCase() === "volumes" && isOpen(i + 1)) {
            volumesKey = i;
        }
    }
    if (rootClose === -1) throw new Error("overview file has an unterminated root block");

    if (volumesKey === -1) {
        const insertAt = tokens[rootClose].start;
        return `${existing.slice(0, insertAt).replace(/\s*$/, "\n")}\t${block}\n${existing.slice(insertAt)}`;
    }

    let blockDepth = 0;
    for (let i = volumesKey + 1; i < tokens.length; i++) {
        if (isOpen(i)) blockDepth++;
        else if (isClose(i) && --blockDepth === 0) {
            return existing.slice(0, tokens[volumesKey].start) + block + existing.slice(tokens[i].end);
        }
    }
    throw new Error(`overview file has an unterminated "Volumes" block`);
};

type KeyValuesToken = { text: string; quoted: boolean; start: number; end: number };

/** Minimal KeyValues1 tokenizer: quoted strings, unquoted words, braces; skips // comments. */
const tokenizeKeyValues = (text: string): KeyValuesToken[] => {
    const tokens: KeyValuesToken[] = [];
    const re = /\/\/[^\n]*|"((?:[^"\\]|\\.)*)"|([{}])|([^\s{}"]+)/g;
    for (const m of text.matchAll(re)) {
        if (m[0].startsWith("//")) continue;
        const quoted = m[1] !== undefined;
        tokens.push({ text: m[1] ?? m[2] ?? m[3], quoted, start: m.index, end: m.index + m[0].length });
    }
    return tokens;
};
