import { inflateSync } from "node:zlib";

// The minimap only ever requests "<name>_radar.psd" or "<name>_radar.tga" (see client.dll), and
// "autogenerated_tga" in the overview selects .tga. So each source PNG is re-encoded pixel-for-pixel
// (no resampling) into an uncompressed 32-bit TGA, the same format the working volumes used.

const PNG_SIGNATURE = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]);

export type RgbaImage = { width: number; height: number; rgba: Buffer };

/** Decodes a non-interlaced 8-bit RGB/RGBA PNG (what Valve's radar exports are). */
export const decodePng = (data: Buffer): RgbaImage => {
    if (!data.subarray(0, 8).equals(PNG_SIGNATURE)) throw new Error("not a PNG file");

    let width = 0;
    let height = 0;
    let channels = 0;
    const idat: Buffer[] = [];
    for (let offset = 8; offset < data.length; ) {
        const length = data.readUInt32BE(offset);
        const type = data.toString("latin1", offset + 4, offset + 8);
        const body = data.subarray(offset + 8, offset + 8 + length);
        if (type === "IHDR") {
            width = body.readUInt32BE(0);
            height = body.readUInt32BE(4);
            const [bitDepth, colorType, , , interlace] = body.subarray(8, 13);
            if (bitDepth !== 8 || (colorType !== 6 && colorType !== 2) || interlace !== 0) {
                throw new Error(
                    `unsupported PNG (bit depth ${bitDepth}, color type ${colorType}, interlace ${interlace}); expected 8-bit RGB/RGBA, non-interlaced`,
                );
            }
            channels = colorType === 6 ? 4 : 3;
        } else if (type === "IDAT") {
            idat.push(body);
        } else if (type === "IEND") {
            break;
        }
        offset += 12 + length;
    }
    if (!channels) throw new Error("PNG has no IHDR chunk");

    const raw = inflateSync(Buffer.concat(idat));
    const stride = width * channels;
    if (raw.length !== (stride + 1) * height) throw new Error("PNG image data has an unexpected size");

    const pixels = Buffer.alloc(stride * height);
    for (let y = 0; y < height; y++) {
        const filter = raw[y * (stride + 1)];
        const src = y * (stride + 1) + 1;
        const dst = y * stride;
        for (let x = 0; x < stride; x++) {
            const left = x >= channels ? pixels[dst + x - channels] : 0;
            const up = y > 0 ? pixels[dst - stride + x] : 0;
            const upLeft = y > 0 && x >= channels ? pixels[dst - stride + x - channels] : 0;
            let predictor: number;
            switch (filter) {
                case 0: predictor = 0; break;
                case 1: predictor = left; break;
                case 2: predictor = up; break;
                case 3: predictor = (left + up) >> 1; break;
                case 4: predictor = paeth(left, up, upLeft); break;
                default: throw new Error(`invalid PNG filter type ${filter} on row ${y}`);
            }
            pixels[dst + x] = (raw[src + x] + predictor) & 0xff;
        }
    }

    if (channels === 4) return { width, height, rgba: pixels };
    const rgba = Buffer.alloc(width * height * 4, 0xff);
    for (let i = 0, j = 0; i < pixels.length; i += 3, j += 4) pixels.copy(rgba, j, i, i + 3);
    return { width, height, rgba };
};

const paeth = (a: number, b: number, c: number) => {
    const p = a + b - c;
    const pa = Math.abs(p - a);
    const pb = Math.abs(p - b);
    const pc = Math.abs(p - c);
    return pa <= pb && pa <= pc ? a : pb <= pc ? b : c;
};

/** Uncompressed 32-bit BGRA TGA, top-left origin, with a TGA 2.0 footer. */
export const encodeTga = ({ width, height, rgba }: RgbaImage): Buffer => {
    const header = Buffer.alloc(18);
    header[2] = 2; // uncompressed true-color
    header.writeUInt16LE(width, 12);
    header.writeUInt16LE(height, 14);
    header[16] = 32;
    header[17] = 0x28; // 8 alpha bits, top-left origin

    const bgra = Buffer.alloc(rgba.length);
    for (let i = 0; i < rgba.length; i += 4) {
        bgra[i] = rgba[i + 2];
        bgra[i + 1] = rgba[i + 1];
        bgra[i + 2] = rgba[i];
        bgra[i + 3] = rgba[i + 3];
    }

    const footer = Buffer.alloc(26);
    footer.write("TRUEVISION-XFILE.", 8, "latin1");
    return Buffer.concat([header, bgra, footer]);
};
